"""initial tables

Revision ID: 2153535df54c
Revises: 
Create Date: 2026-07-01 16:14:54.902930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2153535df54c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenitymapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amenity_keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('screen_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority_tier', sa.Integer(), nullable=False),
    sa.Column('circuit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('na_default', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenitymapping_amenity_keyword'), 'amenitymapping', ['amenity_keyword'], unique=False)
    op.create_index(op.f('ix_amenitymapping_circuit_name'), 'amenitymapping', ['circuit_name'], unique=False)
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('before_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circuitalias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_or_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canonical', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuitalias_raw_or_alias'), 'circuitalias', ['raw_or_alias'], unique=True)
    op.create_table('circuitoverride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('circuit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('screen_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('na_default', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuitoverride_circuit_name'), 'circuitoverride', ['circuit_name'], unique=False)
    op.create_index(op.f('ix_circuitoverride_keyword'), 'circuitoverride', ['keyword'], unique=False)
    op.create_table('detectionjob',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('include_diagnostics', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ttl', sa.DateTime(), nullable=True),
    sa.Column('stats', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_string', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('circuit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('suggested_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('mapping_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewitem')
    op.drop_table('detectionjob')
    op.drop_index(op.f('ix_circuitoverride_keyword'), table_name='circuitoverride')
    op.drop_index(op.f('ix_circuitoverride_circuit_name'), table_name='circuitoverride')
    op.drop_table('circuitoverride')
    op.drop_index(op.f('ix_circuitalias_raw_or_alias'), table_name='circuitalias')
    op.drop_table('circuitalias')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_amenitymapping_circuit_name'), table_name='amenitymapping')
    op.drop_index(op.f('ix_amenitymapping_amenity_keyword'), table_name='amenitymapping')
    op.drop_table('amenitymapping')
    # ### end Alembic commands ###
